# Generated by Django 5.0.4 on 2024-04-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_snapshotschedule_cluster_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshotschedule',
            name='cluster_uuid',
        ),
    ]
