# Generated by Django 5.0.4 on 2024-04-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_snapshotschedule_cluster_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotschedule',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
