# Generated by Django 5.0.4 on 2024-04-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_snapshotschedule_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotschedule',
            name='snapshot_taken',
            field=models.BooleanField(default=False),
        ),
    ]
