# Generated by Django 5.0.4 on 2024-04-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_snapshotschedule_snapshot_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotschedule',
            name='snapshot_execution_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
