# Generated by Django 5.0.4 on 2024-04-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_snapshotschedule_snapshot_execution_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshotschedule',
            name='snapshot_execution_datetime',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
