# Generated by Django 5.0.4 on 2024-05-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_snapshotschedule_snapshot_execution_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotschedule',
            name='snapshot_name',
            field=models.CharField(default='snapshot_by_script', max_length=200),
        ),
    ]
