# Generated by Django 5.0.4 on 2024-05-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_snapshotschedule_snapshot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotschedule',
            name='snapshot_failed',
            field=models.BooleanField(default=False),
        ),
    ]
